name: CI

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

jobs:
  lint:
    name: ESLint Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run ESLint
        run: yarn lint

      - name: Run TypeScript check
        run: yarn tsc --noEmit

  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run unit tests
        run: yarn test:unit

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4 # 升级到 v4
        if: always()
        with:
          name: coverage-report
          path: coverage/

  # e2e-test:
  #   name: E2E Tests
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: '18'
  #         cache: 'yarn'

  #     - name: Install dependencies
  #       run: yarn install --frozen-lockfile

  #     - name: Build application
  #       run: yarn client:prod

  #     - name: Run Cypress E2E tests
  #       uses: cypress-io/github-action@v6
  #       with:
  #         install-command: yarn install --frozen-lockfile
  #         start: yarn client:server
  #         wait-on: 'http://localhost:8080'
  #         wait-on-timeout: 120
  #         browser: chrome
  #         headed: false

  #     - name: Upload Cypress screenshots
  #       uses: actions/upload-artifact@v4 # 升级到 v4
  #       if: failure()
  #       with:
  #         name: cypress-screenshots
  #         path: cypress/screenshots

  #     - name: Upload Cypress videos
  #       uses: actions/upload-artifact@v4 # 升级到 v4
  #       if: always()
  #       with:
  #         name: cypress-videos
  #         path: cypress/videos

  build:
    name: Build Check
    runs-on: ubuntu-latest
    needs: [lint]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build production
        run: yarn client:prod

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4 # 升级到 v4
        with:
          name: build-files
          path: dist/
